language: objective-c
matrix:
  fast_finish: true
env:
  - FORMULA=zeroc-ice34 BREW_OPTS=
  - FORMULA=zeroc-ice34 BREW_OPTS=--with-python
  - FORMULA=zeroc-ice34 BREW_OPTS=--with-java
  - FORMULA=zeroc-ice35 BREW_OPTS=--with-python
  - FORMULA=omero BREW_OPTS=--only-dependencies
before_script:
    - brew update
    - brew tap ome/alt
    - brew tap homebrew/science
    - brew audit Formula/*.rb
    - python check_alias.py
script:
    - if [[ $FORMULA == 'omero' ]]; then sudo pip install Genshi; fi
    - VERBOSE=1 brew install Formula/$FORMULA.rb $BREW_OPTS
    - if [[ $FORMULA != 'omero' ]]; then brew test Formula/$FORMULA.rb; fi
